#!/usr/bin/env bash
#
# First-time local install for testers. Creates data files, sets LAN IP, starts Docker.
#
# Usage:
#   ./scripts/setup.sh              # init missing files + docker compose up --build -d
#   ./scripts/setup.sh --host IP    # force matterHost / WebRTC candidates to IP
#   ./scripts/setup.sh --dev        # npm install + local run (no Docker)
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FORCE_HOST=""
MODE="docker"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host)
      FORCE_HOST="${2:?--host requires an IP address}"
      shift 2
      ;;
    --dev)
      MODE="dev"
      shift
      ;;
    -h|--help)
      sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

detect_lan_ip() {
  if [[ -n "${FORCE_HOST}" ]]; then
    echo "${FORCE_HOST}"
    return
  fi
  if [[ -n "${MATTER_HOST:-}" ]]; then
    echo "${MATTER_HOST}"
    return
  fi

  local ip=""
  if [[ "$(uname -s)" == "Darwin" ]]; then
    local iface
    iface="$(route -n get default 2>/dev/null | awk '/interface:/{print $2; exit}')"
    if [[ -n "${iface}" ]]; then
      ip="$(ipconfig getifaddr "${iface}" 2>/dev/null || true)"
    fi
  else
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    if [[ -z "${ip}" ]]; then
      ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1); exit}' || true)"
    fi
  fi

  if [[ -z "${ip}" ]]; then
    echo "ERROR: Could not detect LAN IP. Pass --host <your-lan-ip> or set MATTER_HOST." >&2
    exit 1
  fi
  echo "${ip}"
}

write_from_example() {
  local example="$1"
  local dest="$2"
  local lan_ip="$3"

  if [[ -f "${dest}" ]]; then
    echo "  keep  ${dest}"
    return
  fi
  if [[ ! -f "${example}" ]]; then
    echo "ERROR: missing template ${example}" >&2
    exit 1
  fi
  sed "s/__LAN_IP__/${lan_ip}/g" "${example}" > "${dest}"
  echo "  create ${dest} (matterHost=${lan_ip})"
}

ensure_cameras_json() {
  if [[ -f data/cameras.json ]]; then
    echo "  keep  data/cameras.json"
    return
  fi
  echo '{"cameras":[]}' > data/cameras.json
  echo "  create data/cameras.json"
}

ensure_env() {
  if [[ -f .env ]]; then
    echo "  keep  .env"
    return
  fi
  cat > .env <<EOF
# Generated by scripts/setup.sh — LAN IP used for Matter pairing QR and WebRTC ICE
MATTER_HOST=${lan_ip}
MATTER_BIND_HOST=${lan_ip}
MATTER_PORT=5550
WEB_PORT=3202
GO2RTC_URL=http://127.0.0.1:3203
EOF
  echo "  create .env"
}

lan_ip="$(detect_lan_ip)"

echo "==> MatterCameras setup"
echo "    LAN IP (matterHost / WebRTC): ${lan_ip}"
echo ""

mkdir -p data

echo "==> Data files"
write_from_example data/config.json.example data/config.json "${lan_ip}"
write_from_example data/go2rtc.yaml.example data/go2rtc.yaml "${lan_ip}"
ensure_cameras_json
ensure_env
echo ""

if [[ "${MODE}" == "dev" ]]; then
  echo "==> Dev mode (Node on host, go2rtc must be reachable at GO2RTC_URL)"
  command -v node >/dev/null || { echo "ERROR: Node.js required for --dev" >&2; exit 1; }
  npm install
  echo ""
  echo "Start with:  npm start"
  echo "Web UI:      http://${lan_ip}:3202"
  exit 0
fi

command -v docker >/dev/null || { echo "ERROR: Docker required. Install Docker or use --dev." >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "ERROR: docker compose plugin not found." >&2; exit 1; }

# docker-compose bind-mounts ./dist; compile on the host so a fresh clone is not empty.
echo "==> Build app (dist/ for Docker bind-mount)"
command -v node >/dev/null || { echo "ERROR: Node.js 22+ required to build dist/. Install Node or use --dev." >&2; exit 1; }
npm ci
npm run build
echo ""

echo "==> Docker compose (host network — required for Matter mDNS)"
docker compose up --build -d
echo ""
docker compose ps
echo ""
echo "==> Ready"
echo "Web UI:  http://${lan_ip}:3202"
echo "go2rtc:  http://${lan_ip}:3203"
echo "Matter:  ${lan_ip}:5550"
echo ""
echo "Next: open the Web UI → Matter pairing QR → add an RTSP camera."
echo "Full guide: docs/INSTALL.md"
